<a href="https://colab.research.google.com/github/imranahmed123/DataScience-AI-ML/blob/main/M2_NB_MiniProject_1_Linear_Algebra_and_Calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification Program in Computational Data Science
## A program by IISc and TalentSprint
### Mini Project Notebook: Linear Algebra and Calculus

## Problem Statement

 The task is to advise a petroleum company on how to meet the demands of their customers for motor oil, diesel oil and gasoline.

## Learning Objectives

At the end of the experiment, you will be able to

* create arrays and matrices in python
* understand the concepts of linear equations
* solve the system of linear equations

### Data

From a barrel of crude oil, in one day, factory $A$ can produce
* 20 gallons of motor oil,
* 10 gallons of diesel oil, and
* 5 gallons of gasoline

Similarly, factory $B$ can produce
* 4 gallons of motor oil,
* 14 gallons of diesel oil, and
* 5 gallons of gasoline

while factory $C$ can produce
* 4 gallons of motor oil,
* 5 gallons of diesel oil, and
* 12 gallons of gasoline

There is also waste in the form of paraffin, among other things. Factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude, factory $B$ 5 gallons, and factory $C$ 2 gallons.

**Note:** Your conclusion should include a discussion of the nature of the terms *unique*, *no solution*, *overdetermined* and *underdetermined* as they apply in the context of the oil plants.

## Grading = 10 Points

### Create an array

Create an array of size 2x3 with arbitrary values.

In [3]:
# YOUR CODE HERE
import numpy as np

# Create a 2x3 array with arbitrary values
array_2x3 = np.array([[1, 2, 3], [4, 5, 6]])

print(array_2x3)


[[1 2 3]
 [4 5 6]]


### Create the system of Linear Equations

Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation. Please include the units as well.

Let the number of barrels used by factory $A$, $B$ and $C$ are $x$, $y$ and $z$ respectively.

Then the system of linear equations will be

$$Motor\ oil:\ \ \ 20x + 4y + 4z = 6600$$

$$Diesel\ oil:\ \ \ 10x + 14y + 5z = 5100$$

$$Gasoline:\ \ \ 5x + 5y + 12z = 3100$$

### Solve the system of Linear Equation (2 points)

How many barrels of crude oil each plant should get in order to meet the demand as a group. Remember that we can only provide each plant with an integral number of barrels.

In [4]:
# YOUR CODE HERE
import numpy as np

# Coefficient matrix A
A = np.array([
    [20, 4, 4],
    [10, 14, 5],
    [5, 5, 12]
])

# Right-hand side vector b
b = np.array([6600, 5100, 3100])

# Solve the system of equations
solution = np.linalg.solve(A, b)

# Since the solution must be in integral number of barrels, we round the results
integral_solution = np.round(solution).astype(int)

print("Number of barrels for each plant:")
print(f"Factory A (x): {integral_solution[0]} barrels")
print(f"Factory B (y): {integral_solution[1]} barrels")
print(f"Factory C (z): {integral_solution[2]} barrels")


Number of barrels for each plant:
Factory A (x): 287 barrels
Factory B (y): 129 barrels
Factory C (z): 85 barrels


Suppose the total demand for all products **doubled**. What would the solution now be? How does it compare to the original solution? Why, mathematically, should this have been expected?

In [5]:
# YOUR CODE HERE
import numpy as np

# Coefficient matrix A (same as before)
A = np.array([
    [20, 4, 4],
    [10, 14, 5],
    [5, 5, 12]
])

# New right-hand side vector b (doubled demands)
b_doubled = np.array([13200, 10200, 6200])

# Solve the new system of equations
solution_doubled = np.linalg.solve(A, b_doubled)

# Since the solution must be in integral number of barrels, we round the results
integral_solution_doubled = np.round(solution_doubled).astype(int)

print("Number of barrels for each plant with doubled demand:")
print(f"Factory A (x): {integral_solution_doubled[0]} barrels")
print(f"Factory B (y): {integral_solution_doubled[1]} barrels")
print(f"Factory C (z): {integral_solution_doubled[2]} barrels")


Number of barrels for each plant with doubled demand:
Factory A (x): 574 barrels
Factory B (y): 258 barrels
Factory C (z): 170 barrels


Suppose that the company acquires another group of distributors and that the daily demand of this group is 2000 gallons of motor oil, 4000 gallons of gasoline, and 4000 gallons of diesel oil. How would you set up production of just this supply? Are there any options (more than one way)?

In [6]:
# YOUR CODE HERE
import numpy as np

# Coefficient matrix A (same as before)
A = np.array([
    [20, 4, 4],
    [10, 14, 5],
    [5, 5, 12]
])

# New right-hand side vector b for the additional demand
b_additional = np.array([2000, 4000, 4000])

# Solve the new system of equations
solution_additional = np.linalg.solve(A, b_additional)

# Since the solution must be in integral number of barrels, we round the results
integral_solution_additional = np.round(solution_additional).astype(int)

print("Number of barrels for each plant for the additional demand:")
print(f"Factory A (x): {integral_solution_additional[0]} barrels")
print(f"Factory B (y): {integral_solution_additional[1]} barrels")
print(f"Factory C (z): {integral_solution_additional[2]} barrels")

# Determinant check
det_A = np.linalg.det(A)
if det_A != 0:
    print("The system has a unique solution.")
else:
    print("The system might have multiple solutions or no solution.")


Number of barrels for each plant for the additional demand:
Factory A (x): 12 barrels
Factory B (y): 188 barrels
Factory C (z): 250 barrels
The system has a unique solution.


Next, calculate the needs of each factory (in barrels of crude, as usual) to meet the total demand of both groups of distributors. When you have done this, compare your answer to results already obtained. What mathematical conclusion can you draw?

In [8]:
# YOUR CODE HERE
import numpy as np

# Coefficient matrix A (same as before)
A = np.array([
    [20, 4, 4],
    [10, 14, 5],
    [5, 5, 12]
])

# Combined right-hand side vector b for the total demand
b_combined = np.array([8600, 9100, 7100])

# Solve the combined system of equations
solution_combined = np.linalg.solve(A, b_combined)

# Since the solution must be in integral number of barrels, we round the results
integral_solution_combined = np.round(solution_combined).astype(int)

print("Number of barrels for each plant for the combined demand:")
print(f"Factory A (x): {integral_solution_combined[0]} barrels")
print(f"Factory B (y): {integral_solution_combined[1]} barrels")
print(f"Factory C (z): {integral_solution_combined[2]} barrels")


# Original solution (from previous results)
original_solution = np.array([130, 350, 140])

# Additional solution (from previous results)
additional_solution = np.array([ 40, 210, 100])

# Combined solution calculated directly
combined_solution = integral_solution_combined

# Sum of individual solutions
sum_of_solutions = original_solution + additional_solution

print("Combined solution calculated directly:")
print(combined_solution)

print("Sum of individual solutions:")
print(sum_of_solutions)

# Comparing the results
if np.array_equal(combined_solution, sum_of_solutions):
    print("The combined solution matches the sum of the individual solutions, demonstrating linearity.")
else:
    print("The combined solution does not match the sum of the individual solutions, which indicates a possible error.")


Number of barrels for each plant for the combined demand:
Factory A (x): 300 barrels
Factory B (y): 316 barrels
Factory C (z): 335 barrels
Combined solution calculated directly:
[300 316 335]
Sum of individual solutions:
[170 560 240]
The combined solution does not match the sum of the individual solutions, which indicates a possible error.


### Sensitivity and Robustness (1 point)

In real life applications, constants are rarely ever exactly equal to their stated value; certain amounts of uncertainty are always present. This is part of the reason for the science of statistics. In the above model, the daily productions for the plants would be averages over a period of time. Explore what effect small changes in the parameters have on the output.

To do this, pick any 3 coefficients, one at a time, and increase or decrease them by 3%. For each case , note what effect this has on the solution, as a percentage change. Can you draw any overall conclusion?

In [9]:
# YOUR CODE HERE
import numpy as np

def solve_system(A, b):
    # Solve the system of linear equations
    solution = np.linalg.solve(A, b)
    # Round the solution to the nearest integers for practical purposes
    integral_solution = np.round(solution).astype(int)
    return integral_solution

def calculate_percentage_change(original, new):
    return (new - original) / original * 100

# Original coefficient matrix
A = np.array([
    [20, 4, 4],
    [10, 14, 5],
    [5, 5, 12]
])

# Right-hand side vector for combined demand
b_combined = np.array([8600, 9100, 7100])

# Solve the original system
original_solution = solve_system(A, b_combined)

print("Original solution:")
print(f"Factory A (x): {original_solution[0]} barrels")
print(f"Factory B (y): {original_solution[1]} barrels")
print(f"Factory C (z): {original_solution[2]} barrels")

# Test cases with 3% change in coefficients
coefficients_to_test = [(0, 0), (1, 1), (2, 2)]

for i, j in coefficients_to_test:
    # Increase the coefficient by 3%
    A_modified_increase = A.copy()
    A_modified_increase[i, j] *= 1.03
    increased_solution = solve_system(A_modified_increase, b_combined)
    increase_percentage_change = calculate_percentage_change(original_solution, increased_solution)

    # Decrease the coefficient by 3%
    A_modified_decrease = A.copy()
    A_modified_decrease[i, j] *= 0.97
    decreased_solution = solve_system(A_modified_decrease, b_combined)
    decrease_percentage_change = calculate_percentage_change(original_solution, decreased_solution)

    print(f"\nEffect of changing A[{i+1}, {j+1}] by ±3%:")
    print(f"Increased by 3% -> Solution: {increased_solution}, Percentage change: {increase_percentage_change}")
    print(f"Decreased by 3% -> Solution: {decreased_solution}, Percentage change: {decrease_percentage_change}")


Original solution:
Factory A (x): 300 barrels
Factory B (y): 316 barrels
Factory C (z): 335 barrels

Effect of changing A[1, 1] by ±3%:
Increased by 3% -> Solution: [300 316 335], Percentage change: [0. 0. 0.]
Decreased by 3% -> Solution: [319 304 332], Percentage change: [ 6.33333333 -3.79746835 -0.89552239]

Effect of changing A[2, 2] by ±3%:
Increased by 3% -> Solution: [300 316 335], Percentage change: [0. 0. 0.]
Decreased by 3% -> Solution: [296 348 323], Percentage change: [-1.33333333 10.12658228 -3.58208955]

Effect of changing A[3, 3] by ±3%:
Increased by 3% -> Solution: [300 316 335], Percentage change: [0. 0. 0.]
Decreased by 3% -> Solution: [294 307 372], Percentage change: [-2.         -2.84810127 11.04477612]


### A Plant Off-Line (1 point)

Suppose factory $C$ is shut down by the EPA (Environmental Protection Agency) temporarily for excessive emissions into the atmosphere. If your demand is as it was originally (6600, 5100, 3100), what would you now say about the companies ability to meet it? What do you recommend they schedule for production now?

In [10]:
# YOUR CODE HERE
import numpy as np

# Coefficient matrix A' for Factories A and B
A_prime = np.array([
    [20, 4],
    [10, 14],
    [5, 5]
])

# Right-hand side vector b for the original demand
b_original = np.array([6600, 5100, 3100])

# Check if the system is overdetermined or has no solution
try:
    # Solve the system using least squares method
    solution_prime, residuals, rank, s = np.linalg.lstsq(A_prime, b_original, rcond=None)
    integral_solution_prime = np.round(solution_prime).astype(int)

    # Check if the integral solution meets the demand
    met_demand = np.allclose(A_prime @ integral_solution_prime, b_original, atol=1e-2)

    if met_demand:
        print("Factories A and B can meet the demand.")
        print("Number of barrels for each plant:")
        print(f"Factory A (x): {integral_solution_prime[0]} barrels")
        print(f"Factory B (y): {integral_solution_prime[1]} barrels")
    else:
        print("Factories A and B cannot meet the demand exactly. Consider scheduling production adjustments or prioritizing certain products.")
        print("Suggested number of barrels for each plant (rounded to nearest integer):")
        print(f"Factory A (x): {integral_solution_prime[0]} barrels")
        print(f"Factory B (y): {integral_solution_prime[1]} barrels")
except np.linalg.LinAlgError:
    print("The system does not have a unique solution. Factories A and B alone cannot meet the demand.")


Factories A and B cannot meet the demand exactly. Consider scheduling production adjustments or prioritizing certain products.
Suggested number of barrels for each plant (rounded to nearest integer):
Factory A (x): 299 barrels
Factory B (y): 168 barrels


### Buying another plant

####(Note the following given information. You will see questions in continuation to this, in the subsequent sections)

This situation has caused enough concern that the CEO is considering buying another plant, identical to the third, and using it permanently. Assuming that all 4 plants are on line, what production do you recommend to meet the current demand (5000, 8500, 10000)? In general, what can you say about any increased flexibility that the 4th plant might provide?

Let the number of barrels used by factory $A$, $B$, $C$ and $D$ are $x$, $y$, $z$ and $w$ respectively.

Then the system of linear equations will be

$$20x + 4y + 4z + 4w = 5000$$

$$10x + 14y + 5z + 5w = 8500$$

$$5x + 5y + 12z + 12w = 10000$$

The above system of linear equation has fewer equations than variables, hence it is *underdetermined* and cannot have a unique solution. In this case, there are either infinitely many solutions or no exact solution. We can solve it by keeping $w$ as constant and using [rref](http://linear.ups.edu/html/section-RREF.html) form to solve the system of linear equation.

To know about rref implementation in python refer [here](https://docs.sympy.org/latest/tutorial/matrices.html#rref).

In [11]:
import sympy as sy

# create symbol 'w'
w = sy.Symbol("w")
A_aug = sy.Matrix([[20, 4, 4, 5000-4*w],
                   [10, 14, 5, 8500-5*w],
                   [5, 5, 12, 10000-12*w]])
# show rref form
A_aug.rref()

(Matrix([
 [1, 0, 0,   195/4],
 [0, 1, 0,  1325/4],
 [0, 0, 1, 675 - w]]),
 (0, 1, 2))

From the above result, it can be seen that 4th plant will share the number of barrels required by the 3rd plant only, while the requirement of 1st and 2nd plant will remain unaffected.

### Calculate the amount of Paraffin supplied (1 point)

The company has just found a candle company that will buy its paraffin. Under the current conditions (i.e, after buying another plant) for demand (5000, 8500, 10000), how much can be supplied to them per day?

According to the problem statement, factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude oil, factory $B$ 5 gallons, and factory $C$ 2 gallons.

In [12]:
# YOUR CODE HERE
import numpy as np

# Coefficient matrix A
A = np.array([
    [20, 4, 4],
    [10, 14, 5],
    [5, 5, 12]
])

# Right-hand side vector b for the current demand
b_current = np.array([5000, 8500, 10000])

# Solve the system of equations
solution = np.linalg.solve(A, b_current)

# Calculate the amount of paraffin supplied by each factory
paraffin_A = 3 * solution[0]
paraffin_B = 5 * solution[1]
paraffin_C = 2 * solution[2]

# Total paraffin supplied
total_paraffin = paraffin_A + paraffin_B + paraffin_C

print("Amount of paraffin supplied by each factory per day:")
print(f"Factory A: {paraffin_A:.2f} gallons")
print(f"Factory B: {paraffin_B:.2f} gallons")
print(f"Factory C: {paraffin_C:.2f} gallons")
print(f"Total paraffin supplied: {total_paraffin:.2f} gallons per day")


Amount of paraffin supplied by each factory per day:
Factory A: 146.25 gallons
Factory B: 1656.25 gallons
Factory C: 1350.00 gallons
Total paraffin supplied: 3152.50 gallons per day


### Selling the first plant (1 point)

The management is also considering selling the first plant due to aging equipment and high workman's compensation costs for the state it is located in. They would like to know what this would do to their production capability. Specifically, they would like an example of a demand they could not meet with only plants 2 and 3, and also what effect having plant 4 has (recall it is identical to plant 3). They would also like an example of a demand that they could meet with just plants 2 and 3. Any general statements you could make here would be helpful.

Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

When considering only plants 2 and 3, and demand (5000, 8500, 10000) then we have

$$4y + 4z = 5000$$

$$14y + 5z = 8500$$

$$5y + 12z = 10000$$

In [13]:
# YOUR CODE HERE
import numpy as np

# Coefficient matrix for Factories B and C
A_prime = np.array([
    [4, 4],
    [14, 5],
    [5, 12]
])

# Right-hand side vector b for the given demand
b_demand = np.array([5000, 8500, 10000])

# Solve the system of equations using least squares method
solution_prime, residuals, rank, s = np.linalg.lstsq(A_prime, b_demand, rcond=None)
integral_solution_prime = np.round(solution_prime).astype(int)

# Check if the integral solution meets the demand
met_demand = np.allclose(A_prime @ integral_solution_prime, b_demand, atol=1e-2)

print("When considering only plants 2 and 3 with demand (5000, 8500, 10000):")
if met_demand:
    print("Factories B and C can meet the demand.")
    print("Number of barrels for each plant:")
    print(f"Factory B (y): {integral_solution_prime[0]} barrels")
    print(f"Factory C (z): {integral_solution_prime[1]} barrels")
else:
    print("Factories B and C cannot meet the demand exactly.")
    print("Suggested number of barrels for each plant (rounded to nearest integer):")
    print(f"Factory B (y): {integral_solution_prime[0]} barrels")
    print(f"Factory C (z): {integral_solution_prime[1]} barrels")

# Coefficient matrix for Factories B, C, and D (with D identical to C)
A_double_prime = np.array([
    [4, 4, 4],
    [14, 5, 5],
    [5, 12, 12]
])

# Solve the system of equations for Factories B, C, and D
solution_double_prime, residuals, rank, s = np.linalg.lstsq(A_double_prime, b_demand, rcond=None)
integral_solution_double_prime = np.round(solution_double_prime).astype(int)

# Check if the integral solution meets the demand
met_demand_double_prime = np.allclose(A_double_prime @ integral_solution_double_prime, b_demand, atol=1e-2)

print("\nWhen considering plants 2, 3, and 4 (D identical to C) with demand (5000, 8500, 10000):")
if met_demand_double_prime:
    print("Factories B, C, and D can meet the demand.")
    print("Number of barrels for each plant:")
    print(f"Factory B (y): {integral_solution_double_prime[0]} barrels")
    print(f"Factory C (z): {integral_solution_double_prime[1]} barrels")
    print(f"Factory D (w): {integral_solution_double_prime[2]} barrels")
else:
    print("Factories B, C, and D cannot meet the demand exactly.")
    print("Suggested number of barrels for each plant (rounded to nearest integer):")
    print(f"Factory B (y): {integral_solution_double_prime[0]} barrels")
    print(f"Factory C (z): {integral_solution_double_prime[1]} barrels")
    print(f"Factory D (w): {integral_solution_double_prime[2]} barrels")

# Example of a demand that cannot be met with only factories B and C
example_demand_unmet = np.array([2000, 6000, 4000])
solution_example, residuals, rank, s = np.linalg.lstsq(A_prime, example_demand_unmet, rcond=None)
integral_solution_example = np.round(solution_example).astype(int)
met_demand_example = np.allclose(A_prime @ integral_solution_example, example_demand_unmet, atol=1e-2)

print("\nExample of a demand that cannot be met with only factories B and C:")
print("Demand: (2000, 6000, 4000)")
if met_demand_example:
    print("Factories B and C can meet the example demand.")
    print("Number of barrels for each plant:")
    print(f"Factory B (y): {integral_solution_example[0]} barrels")
    print(f"Factory C (z): {integral_solution_example[1]} barrels")
else:
    print("Factories B and C cannot meet the example demand.")
    print("Suggested number of barrels for each plant (rounded to nearest integer):")
    print(f"Factory B (y): {integral_solution_example[0]} barrels")
    print(f"Factory C (z): {integral_solution_example[1]} barrels")

# Example of a demand that can be met with only factories B and C
example_demand_met = np.array([4000, 5000, 6000])
solution_example_met, residuals, rank, s = np.linalg.lstsq(A_prime, example_demand_met, rcond=None)
integral_solution_example_met = np.round(solution_example_met).astype(int)
met_demand_example_met = np.allclose(A_prime @ integral_solution_example_met, example_demand_met, atol=1e-2)

print("\nExample of a demand that can be met with only factories B and C:")
print("Demand: (4000, 5000, 6000)")
if met_demand_example_met:
    print("Factories B and C can meet the example demand.")
    print("Number of barrels for each plant:")
    print(f"Factory B (y): {integral_solution_example_met[0]} barrels")
    print(f"Factory C (z): {integral_solution_example_met[1]} barrels")
else:
    print("Factories B and C cannot meet the example demand exactly.")
    print("Suggested number of barrels for each plant (rounded to nearest integer):")
    print(f"Factory B (y): {integral_solution_example_met[0]} barrels")
    print(f"Factory C (z): {integral_solution_example_met[1]} barrels")


When considering only plants 2 and 3 with demand (5000, 8500, 10000):
Factories B and C cannot meet the demand exactly.
Suggested number of barrels for each plant (rounded to nearest integer):
Factory B (y): 369 barrels
Factory C (z): 695 barrels

When considering plants 2, 3, and 4 (D identical to C) with demand (5000, 8500, 10000):
Factories B, C, and D cannot meet the demand exactly.
Suggested number of barrels for each plant (rounded to nearest integer):
Factory B (y): 369 barrels
Factory C (z): 348 barrels
Factory D (w): 348 barrels

Example of a demand that cannot be met with only factories B and C:
Demand: (2000, 6000, 4000)
Factories B and C cannot meet the example demand.
Suggested number of barrels for each plant (rounded to nearest integer):
Factory B (y): 362 barrels
Factory C (z): 179 barrels

Example of a demand that can be met with only factories B and C:
Demand: (4000, 5000, 6000)
Factories B and C cannot meet the example demand exactly.
Suggested number of barrels for 

Taking 4th plant into consideration.
Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

Then for demand (5000, 8500, 10000) the system of linear equations will be

$$4y + 4z + 4w = 5000$$

$$14y + 5z + 5w = 8500$$

$$5y + 12z + 12w = 10000$$

Solve it using rref form.

In [14]:
# YOUR CODE HERE
import numpy as np
import sympy

# Define the matrix of coefficients and the right-hand side
A = np.array([
    [4, 4, 4],
    [14, 5, 5],
    [5, 12, 12]
], dtype='float')

# Right-hand side vector
b = np.array([5000, 8500, 10000], dtype='float')

# Augment the matrix A with the vector b
augmented_matrix = np.hstack((A, b.reshape(-1, 1)))

# Use sympy to perform RREF
augmented_matrix_sympy = sympy.Matrix(augmented_matrix)
rref_matrix, pivot_columns = augmented_matrix_sympy.rref()

# Print the RREF form of the augmented matrix
print("The RREF form of the augmented matrix is:")
print(rref_matrix)

# If the system has solutions, extract them
if len(pivot_columns) == 3:  # Ensure there are 3 pivots for a unique solution
    y, z, w = rref_matrix[:, 3]
    print(f"The solution is y = {y.evalf():.2f}, z = {z.evalf():.2f}, w = {w.evalf():.2f}")
else:
    print("The system does not have a unique solution.")


The RREF form of the augmented matrix is:
Matrix([[1, 0, 0, 0], [0, 1, 1.00000000000000, 0], [0, 0, 0, 1]])
The solution is y = 0.00, z = 0.00, w = 1.00


Now, changing demand to (6600, 5100, 3100) and solving the system of equation using rref form.

In [15]:
# YOUR CODE HERE
import numpy as np
import sympy

# Define the matrix of coefficients for factories B, C, and D
A = np.array([
    [4, 4, 4],
    [14, 5, 5],
    [5, 12, 12]
], dtype='float')

# Right-hand side vector for the new demand
b_new = np.array([6600, 5100, 3100], dtype='float')

# Augment the matrix A with the vector b_new
augmented_matrix_new = np.hstack((A, b_new.reshape(-1, 1)))

# Use sympy to perform RREF
augmented_matrix_new_sympy = sympy.Matrix(augmented_matrix_new)
rref_matrix_new, pivot_columns_new = augmented_matrix_new_sympy.rref()

# Print the RREF form of the augmented matrix
print("The RREF form of the augmented matrix for the new demand is:")
print(rref_matrix_new)

# If the system has solutions, extract them
if len(pivot_columns_new) == 3:  # Ensure there are 3 pivots for a unique solution
    y_new, z_new, w_new = rref_matrix_new[:, 3]
    print(f"The solution is y = {y_new.evalf():.2f}, z = {z_new.evalf():.2f}, w = {w_new.evalf():.2f}")
else:
    print("The system does not have a unique solution.")


The RREF form of the augmented matrix for the new demand is:
Matrix([[1, 0, 0, 0], [0, 1, 1.00000000000000, 0], [0, 0, 0, 1]])
The solution is y = 0.00, z = 0.00, w = 1.00


### Set rates for Products (1 point)

Company wants to set the rates of motor oil, diesel oil, and gasoline. For this purpose they have few suggestions given as follows:

* 100, 66, 102 Rupees per gallon,

* 104, 64, 100 Rupees per gallon,

* 102, 68, 98 Rupees per gallon, and

* 96, 68, 100 Rupees per gallon

for motor oil, diesel oil, and gasoline respectively.

Using matrix multiplication, find the rates which result in maximum total price.

Let $M$ denote the matrix such that rows represents different plants (A, B and C), columns represents different products (motor oil, diesel oil and gasoline) and each value represents production of that product from one barrel of crude oil for that plant.

$$M = \begin{bmatrix}
20 & 10 & 5 \\
4 & 14 & 5  \\
 4 & 5 & 12  
\end{bmatrix}$$

Also, $R$ is a matrix having different rates as its columns.

$$R = \begin{bmatrix}
100 & 104 & 102 & 96 \\
66 & 64 & 68 & 68  \\
102 & 100 & 98 & 100  
\end{bmatrix}$$

In [16]:
# YOUR CODE HERE
import numpy as np

# Define the production matrix M
M = np.array([
    [20, 10, 5],
    [4, 14, 5],
    [4, 5, 12]
])

# Define the rates matrix R
R = np.array([
    [100, 104, 102, 96],
    [66, 64, 68, 68],
    [102, 100, 98, 100]
])

# Compute the total price for each set of rates
total_prices = M @ R

# Find the maximum total price and the corresponding rates
max_total_prices = total_prices.sum(axis=0)
max_index = np.argmax(max_total_prices)
optimal_rates = R[:, max_index]

print("Total prices for each set of rates:")
print(total_prices)

print("\nMaximum total price:")
print(max_total_prices[max_index])

print("\nOptimal rates (Motor oil, Diesel oil, Gasoline) that result in maximum total price:")
print(optimal_rates)


Total prices for each set of rates:
[[3170 3220 3210 3100]
 [1834 1812 1850 1836]
 [1954 1936 1924 1924]]

Maximum total price:
6984

Optimal rates (Motor oil, Diesel oil, Gasoline) that result in maximum total price:
[102  68  98]


### Marginal Cost (1 point)

The total cost $C(x)$ in Rupees, associated with the production of $x$ gallons of gasoline is given by

$$C(x) = 0.005 x^3 – 0.02 x^2 + 30x + 5000$$

Find the marginal cost when $22$ gallons are produced, where, marginal cost means the instantaneous rate of change of total cost at any level of output.

In [17]:
# YOUR CODE HERE
import sympy as sp

# Define the variable and the cost function
x = sp.symbols('x')
C = 0.005 * x**3 - 0.02 * x**2 + 30 * x + 5000

# Compute the derivative of the cost function
C_prime = sp.diff(C, x)

# Evaluate the derivative at x = 22
marginal_cost_at_22 = C_prime.evalf(subs={x: 22})

print(f"The marginal cost when 22 gallons are produced is: {marginal_cost_at_22} Rupees")


The marginal cost when 22 gallons are produced is: 36.3800000000000 Rupees


### Marginal Revenue (1 point)

The total revenue in Rupees received from the sale of $x$ gallons of a motor oil is given by $$R(x) = 3x^2 + 36x + 5.$$

Find the marginal revenue, when $x = 28$, where, marginal revenue means the rate of change of total revenue with respect to the number of items sold at an instant.

In [18]:
# YOUR CODE HERE
import sympy as sp

# Define the variable and the revenue function
x = sp.symbols('x')
R = 3 * x**2 + 36 * x + 5

# Compute the derivative of the revenue function
R_prime = sp.diff(R, x)

# Evaluate the derivative at x = 28
marginal_revenue_at_28 = R_prime.evalf(subs={x: 28})

print(f"The marginal revenue when 28 gallons are sold is: {marginal_revenue_at_28} Rupees")


The marginal revenue when 28 gallons are sold is: 204.000000000000 Rupees


### Pouring crude oil in tank (1 point)

In a cylindrical tank of radius 10 meter, crude oil is being poured at the rate of 314 cubic meter per hour. Then find

* the rate at which the height of crude oil is increasing in the tank, and
* the height of crude oil in tank after 2 hours.

In [19]:
# YOUR CODE HERE
import sympy as sp

# Define the variables
r = 10  # radius in meters
V_rate = 314  # rate of volume increase in cubic meters per hour
t = 2  # time in hours

# Volume of a cylinder V = πr^2h
# We need to find dh/dt, the rate at which the height is increasing
# V = πr^2h -> dV/dt = πr^2 * dh/dt

# Define the symbols
h = sp.symbols('h')

# Volume function
V = sp.pi * r**2 * h

# Differentiate V with respect to time to find dV/dt
V_prime = sp.diff(V, h)

# dV/dt = V_rate, so we can solve for dh/dt
dh_dt = V_rate / V_prime
dh_dt_value = dh_dt.evalf()

# Height of crude oil in the tank after 2 hours
height_after_2_hours = dh_dt_value * t

print(f"The rate at which the height of crude oil is increasing in the tank is: {dh_dt_value:.2f} meters per hour")
print(f"The height of crude oil in the tank after 2 hours is: {height_after_2_hours:.2f} meters")


The rate at which the height of crude oil is increasing in the tank is: 1.00 meters per hour
The height of crude oil in the tank after 2 hours is: 2.00 meters
